import Link from 'next/link';
import { ArrowLeft, AlertTriangle } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer — CompatIQ',
  description: 'Important limitations and advisory notices for CompatIQ results.',
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#050a14] py-12 px-6">
      <div className="max-w-3xl mx-auto space-y-8">

        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-slate-400 hover:text-slate-200 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" /> Back
        </Link>

        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500 flex items-center justify-center flex-shrink-0 mt-0.5">
            <AlertTriangle className="h-5 w-5 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-extrabold text-white">Disclaimer</h1>
            <p className="text-slate-400 text-sm mt-1">Last updated: May 2026</p>
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 px-6 py-6 space-y-6 text-slate-700">

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">Advisory only — not a guarantee</h2>
            <p className="text-sm leading-relaxed">
              All results generated by CompatIQ — including compatibility assessments, purpose fit ratings, upgradeability scores, parts suggestions, and review signals — are advisory only. They are based on publicly available information and automated analysis. They do not constitute a guarantee of performance, compatibility, availability, or value.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">Specifications may be incomplete</h2>
            <p className="text-sm leading-relaxed">
              CompatIQ extracts device specifications from product pages, search results, and other public sources. Some pages block automated access, use JavaScript rendering, or contain incomplete information. As a result, the specifications shown may be partial, estimated from the product URL, or supplemented by you manually. Always cross-check specifications against the official product page or manufacturer before making a purchasing or repair decision.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">Prices and availability</h2>
            <p className="text-sm leading-relaxed">
              Prices, stock availability, and product listings shown by CompatIQ are pulled from live search and shopping APIs at the time of your query. They may differ from what you see when you visit the store directly. CompatIQ is not responsible for price discrepancies, out-of-stock items, or changes in product availability.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">Parts compatibility</h2>
            <p className="text-sm leading-relaxed">
              Parts compatibility suggestions are generated based on the device model, specifications, and component type you provide. They do not substitute for verification with the part supplier or a qualified technician. Installing an incompatible part can damage your device. CompatIQ accepts no liability for any damage, data loss, or cost resulting from purchasing or installing a part based on its suggestions.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">Review signals</h2>
            <p className="text-sm leading-relaxed">
              Review signals are sourced from public web searches and aggregated automatically. They may include reviews for similar or related models rather than your exact device configuration. They reflect the opinions of third parties and should not be treated as a comprehensive or authoritative assessment of any product.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">Warranty and serial lookup</h2>
            <p className="text-sm leading-relaxed">
              Warranty status and serial number lookup results are retrieved from manufacturer APIs or public support pages where available. These results may not reflect the most current warranty status and should be verified directly with the manufacturer or authorised service centre before making any warranty claim.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-800">No affiliation</h2>
            <p className="text-sm leading-relaxed">
              CompatIQ is an independent tool. It is not affiliated with, endorsed by, or partnered with any device manufacturer, retailer, or service provider whose products or listings may appear in its results.
            </p>
          </section>

        </div>

        <div className="flex gap-4 text-sm">
          <Link href="/privacy" className="text-slate-400 hover:text-slate-200 underline underline-offset-2 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="text-slate-400 hover:text-slate-200 underline underline-offset-2 transition-colors">Terms of Use</Link>
        </div>

      </div>
    </div>
  );
}
